replicaCount: 1

api:
  image:
    repository: user-api-server
    tag: latest
    pullPolicy: Never
  ports:
    - 10302
    - 20113
  config:
    enableKubernetes: "kubernetes"
  volumes:
    - name: openim-config
      configMap:
        name: openim-config

rpc:
  image:
    repository: "user-rpc-server"
    tag: "latest"
    pullPolicy: "Never"
  ports:
    - 10310  # 容器的端口
    - 20100  # 容器的端口
  config:
    enableKubernetes: "kubernetes"  # 部署类型，确保为字符串
  volumes:
    - name: openim-config
      configMap:
        name: openim-config


## MongoDB 配置
mongodb:
  auth:
    enabled: true
    rootPassword: openIM1234
    username: openIM
    password: openIM123
    database: admin
  fullnameOverride: mongodb-service
  replicaSet:
    enabled: true
    replicas: 1  # 设置为 1 代表单节点模式，如果需要副本集，增加副本数

  persistence:
    enabled: true
    size: 1Gi  # 设置存储大小为 1Gi

  # 如果使用现有 Secret，可以指定 existingSecret
  existingSecret: "mongo-secret"
