replicaCount: 1

api:
  image:
    repository: user-api-server
    tag: latest
    pullPolicy: Never
  ports:
    - containerPort: 10302
    - containerPort: 20113
  config:
    enableKubernetes: "kubernetes"
  volumes:
    - name: openim-config
      configMap:
        name: openim-config

rpc:
  image:
    repository: "user-rpc-server"
    tag: "latest"
    pullPolicy: "Never"
  ports:
    - 10310  # 容器的端口
    - 20100  # 容器的端口
  config:
    enableKubernetes: "kubernetes"  # 部署类型，确保为字符串
  volumes:
    - name: openim-config
      configMap:
        name: openim-config

mongo:
  image:
    repository: mongo
    tag: "6.0.2"
    pullPolicy: IfNotPresent
  replicaCount: 1
  storage:
    size: 1Gi
  secretName: mongo-secret
  env:
    - name: MONGO_INITDB_ROOT_USERNAME
      valueFrom:
        secretKeyRef:
          name: mongo-secret
          key: mongo_initdb_root_username
    - name: MONGO_INITDB_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mongo-secret
          key: mongo_initdb_root_password
